SELECT 
      T1. LEFT_HAND_FINGER1
     ,T1. LEFT_HAND_FINGER4
     ,T2.RIGHT_HAND_FINGER1
     ,T2. RIGHT_HAND_FINGER4
(SELECT 
        T1.ID
       ,T1.FINGER AS LEFT_HAND_FINGER1
       ,T2.FINGER AS LEFT_HAND_FINGER4
FROM HAND T1
JOIN HAND T2
ON T1.ID = T2.ID
WHERE T1.ID_FINGER = 1
AND T2.ID_FINGER = 4 ) T1
JOIN 
(SELECT 
       T1.ID
      ,T1.FINGER AS RIGHT_HAND_FINGER1
      ,T2.FINGER AS RIGHT_HAND_FINGER4
FROM HAND T1
JOIN HAND T2
ON T1.ID = T2.ID
WHERE T1.ID_FINGER = 1
AND T2.ID_FINGER = 4 ) T2
ON T1.ID = T2.ID;
